/**
 * Sliding-puzzle solvability check.
 *
 * NOTE: Because we use the legal-moves shuffle (shuffle.js), every puzzle
 * generated by this app is already guaranteed solvable. This utility is
 * provided for reference / external use.
 *
 * Rules (target: [1,2,...,N-1,0], blank at end):
 *  - Odd  column count → solvable iff inversion count is even.
 *  - Even column count → solvable iff (inversions + blank's row from bottom) is odd.
 *
 * @param {number[]} tiles - flat tile array (0 = blank)
 * @param {number}   rows
 * @param {number}   cols
 * @returns {boolean}
 */
export function isSolvable(tiles, rows, cols) {
  const flat = tiles.filter(v => v !== 0);

  let inversions = 0;
  for (let i = 0; i < flat.length - 1; i++) {
    for (let j = i + 1; j < flat.length; j++) {
      if (flat[i] > flat[j]) inversions++;
    }
  }

  if (cols % 2 === 1) {
    // Odd-width grid: solvable iff inversions even
    return inversions % 2 === 0;
  }

  // Even-width grid: factor in blank row position from bottom (1-based)
  const blankIdx         = tiles.indexOf(0);
  const blankRowFromBottom = rows - Math.floor(blankIdx / cols); // 1-based

  if (blankRowFromBottom % 2 === 0) {
    return inversions % 2 === 1;
  }
  return inversions % 2 === 0;
}
